id: auth-misconfig
name: Basic Auth Misconfiguration
severity: medium

requests:
  - path: /
    headers:
      Authorization:
        - "Basic YWRtaW46YWRtaW4="

matchers:
  - type: status
    value: 200
